### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by nicolas-grekas**

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
Now with green CI

**Review by kelunik — COMMENTED** [review]
I don't like exposing the resource, let's discuss other possible solutions in the other PR.

**Comment by nicolas-grekas** [comment]
Why not btw?

**Comment by kelunik** [comment]
Because resources are a leaky abstraction, generally deprecated and expected to be removed in the long run and replaced by objects, which would make this a BC break here, which can be rather easily avoided by avoiding to expose resources where possible. If we don't expose the resource here, we can easily switch to another implementation if OpenSSL is not available, for example. Resources are an implementation detail here.

**Comment by nicolas-grekas** [comment]
ACK. PR is now updated with the CI-fix only. Green.

**Comment by kelunik** [comment]
Thanks. I will look into implementing the missing features for the Symfony PR in the coming days.

**Pull request merged**
